### ISSUE TITLE
Unable to open probably not HashFS file

### ISSUE THREAD

**Issue by n4vi98** [sk-zk/Extractor#13]
Is this kind of mod file not supported with the extractor?
![Screenshot 2024-09-27 163123](https://github.com/user-attachments/assets/0a8a4818-1457-406b-a18e-a5adf16e4b63)

https://pixeldrain.com/u/DzTSE6iR

**Comment by mario50245** [comment]
It means you have AEM lock!

**Comment by sk-zk** [comment]
This is not a HashFS file, buit a ZIP file with deliberately nonsensical local file headers, in this case having been replaced by a watermark of the tool that created it. ETS2/ATS can read these just fine because they only look at the central directory record and ignore local file headers completely, but conventional tools generally fail to extract anything because of this, if they can even open them at all.

I previously considered ZIP to be out of scope for this tool, but since there appear to be more of these things around than I'd assumed, I've added a ZIP reader to the extractor which can unzip these kinds of files.

**Comment by n4vi98** [comment]
thanks 😄
