### ISSUE TITLE
strange format scs file

### ISSUE THREAD

**Issue by CrVault** [sk-zk/Extractor#2]
Hello, I would like to start by thanking you for creating the tool.
I have a scs file with a strange hexadecimal, it is causing some problems with extraction, especially in raw mode.
https://www.mediafire.com/file/wyxh8vqiwpjdvqu/Scania_file.scs/file

If you can take a look. Thank you very much in advance

**Comment by CrVault** [comment]
I'm having an inconsistency when extracting the files. I have entries that have additional characters, I believe it could be something in this type of file.
![image](https://github.com/sk-zk/Extractor/assets/146602819/ff092ea1-686b-4bc5-98f7-4b53c1a7b086)

From what I've seen, this also modifies internal files in the scs file and causes errors when loading the mod. I tried replacing all the entries using a hex editor but it doesn't seem to work for all file types.

When it is readable:â¡
in hexa: E2 81 A1

**Comment by sk-zk** [comment]
I didn't get what you were talking about at first, but I know what's going on here now.

Let's take one of the paths from your screenshot, minus the _very suspicious_ whitespace:
`/vehicle/truck/ntg_lgmods/anim_ext/win_open_ori.pmg`

If you look up the hash of this string in the archive, you will find one of the junk entries with an invalid offset. However, as you've noticed, the .sii files contain some extra bytes in their paths. What are those? Well, let's open the .sii file where the associated .pmd of the file above is referenced, and paste that string into a Unicode analyzer:

<img src="https://i.imgur.com/dtBgmRi.png" width=150>

As you can see, the extra bytes are the Unicode character U+2061 (0x080D), which is invisible in most fonts. This is not a bug: the directories are in fact called `vehicle\u080D` etc. as an obfuscation technique. If you call the extractor with _this_ path, as UTF-8 (which it supports now - I thought paths had to be ASCII, whoops), it will extract the actual file instead of the decoy. This should allow you to unpack the mod.

---

> I did some tests on the mod image file, it was not extracted with the name described in the manifest file

I can't replicate this. The only image referenced in `manifest.sii` is `new.jpg`, which extracts correctly
