### ISSUE TITLE
 extraction is not achieved

### ISSUE THREAD

**Issue by mario50245** [sk-zk/Extractor#7]
Hello. I tried to do the extraction but it asks me to use --raw when using it, it still doesn't allow me to use -p, -a,

![image](https://github.com/user-attachments/assets/bdcb5d8d-4af6-4ad4-8ca9-d8ce2037b451)
   

![image](https://github.com/user-attachments/assets/fd755d87-e8f2-4427-a26c-fffd5feb98de)

...  I don't know if giving up this hashfs thing for someone who is basic in computing is too complicated. You have to know a lot about cybersecurity to specify the issue of hashes and especially with hexadecimal code.

**Comment by sk-zk** [comment]
`-a` is used to extract all .scs files in a directory; don't use it for a single .scs file. Try `-p=/def,/manifest.sii` to get started.

**Comment by mario50245** [comment]
Hello how are you ?? I only managed to unlock the def.

The command that appeared above -p=/def,/manifest.sii indicates that it does not work.

and it doesn't work when /manifest.sii is left blank

![image](https://github.com/user-attachments/assets/b4362687-da89-41ac-9a67-d72963f038f8)

where the arrow indicates cuts the command completely

![image](https://github.com/user-attachments/assets/dabb2dd1-36bc-40d6-9bae-be18bd0e3115)


and in what is an example in the sound folder it worked on 1 bus and on the other it didn't work. here is an example in a single image

![image](https://github.com/user-attachments/assets/e38823c5-446b-46d5-b867-4cb4eca0939b)

https://drive.google.com/file/d/1vhIGMbg13fdNi1DNmubZCmLXhKU6g2GL/view?usp=sharing 

The link I attached is the mod (bus) that does not work

**Comment by sk-zk** [comment]
>The command that appeared above -p=/def,/manifest.sii indicates that it does not work 
>[...]
>where the arrow indicates cuts the command completely

TIL that commas have a special meaning in PowerShell. I've never used it so I didn't know about that. Wrap that parameter in single quotes: `'-p=/def,/manifest.sii'`

>and in what is an example in the sound folder it worked on 1 bus and on the other it didn't work. here is an example in a single image

The extractor can't find `/sound` in the second mod because the modder has intentionally left out that directory listing as an obfuscation technique. This means that you can only extract the sound files if you know their absolute paths, which you can find in `/def`. 

I'm a bit out of my depth here because I don't actually know how the sound system works, but searching for definition files containing "sound" in their name yields the following:

```
/def/vehicle/truck/mp135.mx/cabin/sound.sui
/def/vehicle/truck/mp135.mx/chassis/sound.sui
/def/vehicle/truck/mp135.mx/engine/sound_mp6x2.sui
/def/vehicle/truck/mp135.mx/interior/sound_effects.sui
/def/vehicle/truck/mp135.mx/interior/sound_effects_units.sui
/def/vehicle/truck/mp135.mx/interior/sound_mp6x2.sui
/def/vehicle/truck/mp135.mx/transmission/sound.sui
```

Starting with the first, we find the following paths:

```
/def/vehicle/truck/mp135.mx/cabin/buzina_ar.soundref
/def/vehicle/truck/mp135.mx/cabin/buzina.soundref
```

And in those files, we find this path, which can be extracted:
```
/sound/truck/claxon/buzina.bank
```

Along with the accompanying `guids` file: `/sound/truck/claxon/buzina.bank.guids`

And so on, and so forth. You get the idea.

**Comment by mario50245** [comment]
![image](https://github.com/user-attachments/assets/4da82178-2e2a-40ad-aa23-1a26d6a0c3ba)
 
Indeed, my dear, I was right, indeed, it was with a single quote.

Could it be that this is specifically obfuscated as the hashfs was reinforced there by this line in the hexadecimal editor.

![image](https://github.com/user-attachments/assets/157baaf2-3613-4da0-bef8-e0bb27b57f9e)


Previously, the options that I marked were not there in versions 1.47, 1.48 and in 1.49 that was already added. Could it be that that is why they are reinforced and blocked there?

**Comment by sk-zk** [comment]
The first field you highlighted is the salt. The second field is the offset of the entry table. Nothing about this is new in any way, and nothing is being "reinforced" or "blocked" here.
